# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6N3JjntxeoyxwwnJorIqv32f4ZuoTjW
"""

from flask import Flask, request, send_file
import fitz
import pandas as pd
import re
import os
from datetime import datetime
from io import BytesIO

app = Flask(__name__)

# Cargar CIE10 una sola vez
cie10_df = pd.read_excel("CIE10.xlsx")

# Función para calcular días
def calculate_total_days(start_date_str, end_date_str):

    if start_date_str is None or end_date_str is None:
        return None

    try:
        start_date = datetime.strptime(start_date_str, "%d/%m/%Y")
        end_date = datetime.strptime(end_date_str, "%d/%m/%Y")

        total_days = (end_date - start_date).days + 1

        return total_days

    except:
        return None


@app.route('/procesar', methods=['POST'])
def procesar():

    archivos = request.files.getlist("files")

    all_data = []

    for archivo in archivos:

        pdf_document = fitz.open(stream=archivo.read(), filetype="pdf")

        first_page = pdf_document[0]

        text = first_page.get_text("text")

        patient_name = None
        identification = None
        diagnosis = None
        date_of_attention = None
        order = None
        prorogation = None
        start_date = None
        end_date = None
        eps = None
        tipo_incapacidad = None
        grupo_servicio = None

        # REGEX

        patient_name_match = re.search(
            r'PRESCRIPCIÓN DE INCAPACIDAD/LICENCIA DE MATERNIDAD\s*([^\n]*)\s*Identificación:',
            text
        )

        if patient_name_match:
            patient_name = patient_name_match.group(1).strip()

        identification_match = re.search(
            r'Identificación:\s*CC\s*(\d+)',
            text
        )

        if identification_match:
            identification = identification_match.group(1).strip()

        diagnosis_code_match = re.search(
            r'\b([A-Z]\d{2,3}[A-Z]?)\b',
            text
        )

        if diagnosis_code_match:
            diagnosis = diagnosis_code_match.group(1).strip()

        eps_lines = re.findall(r'EPS:\s*(.*)', text)

        if eps_lines:
            eps = eps_lines[-1].strip()

        start_date_match = re.search(
            r'Fecha Inicio:\s*(\d{2}/\d{2}/\d{4})',
            text
        )

        if start_date_match:
            start_date = start_date_match.group(1).strip()

        end_date_match = re.search(
            r'Fecha Fin:\s*(\d{2}/\d{2}/\d{4})',
            text
        )

        if end_date_match:
            end_date = end_date_match.group(1).strip()

        date_of_attention_match = re.search(
            r'Orden:\s*\d+\n(\d{4}/\d{2}/\d{2})',
            text
        )

        if date_of_attention_match:
            date_of_attention = date_of_attention_match.group(1).strip()

        order_match = re.search(r'Orden:\s*(\d+)', text)

        if order_match:
            order = order_match.group(1).strip()

        prorogation_match = re.search(
            r'Prórroga:\s*(NO|SI)',
            text
        )

        if prorogation_match:
            prorogation = prorogation_match.group(1).strip()

        tipo_incapacidad_match = re.search(
            r'Tipo Incapacidad:\s*(.*)',
            text
        )

        if tipo_incapacidad_match:
            tipo_incapacidad = tipo_incapacidad_match.group(1).strip()

        grupo_servicio_match = re.search(
            r'Grupo Servicio:\s*(.*)',
            text
        )

        if grupo_servicio_match:
            grupo_servicio = grupo_servicio_match.group(1).strip()

        total_days = calculate_total_days(
            start_date,
            end_date
        )

        all_data.append({

            "Documento": identification,

            "Paciente": patient_name,

            "CONCATENAR":
            f"{identification} {patient_name}"
            if identification and patient_name else None,

            "Fecha de Inicio": start_date,

            "Fecha de Fin": end_date,

            "Total de Días": total_days,

            "Dias": None,

            "EPS": eps,

            "Observacion": None,

            "DX": diagnosis,

            "FECHA": date_of_attention,

            "ORDEN": order,

            "PRORROGA": prorogation,

            "Tipo Incapacidad": tipo_incapacidad,

            "Grupo Servicio": grupo_servicio

        })

        pdf_document.close()

    # Crear DataFrame
    df = pd.DataFrame(all_data)

    # Merge CIE10
    df = pd.merge(
        df,
        cie10_df,
        left_on='DX',
        right_on='Codigo',
        how='left'
    )

    # Concatenar descripción
    df['DX'] = df['DX'] + ' ' + df['Nombre']

    # Eliminar columnas
    df = df.drop(columns=['Nombre', 'Codigo'])

    # Fecha actual
    df.insert(
        0,
        'Fecha envio dra',
        datetime.now().strftime("%d/%m/%Y")
    )

    # Crear Excel en memoria
    output = BytesIO()

    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False)

    output.seek(0)

    return send_file(
        output,
        download_name="resultado.xlsx",
        as_attachment=True,
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


if __name__ == '__main__':
    app.run(debug=True)